version: '3'
services:
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./nginx/log:/var/log/nginx
      - ./h2o/log:/var/log/h2o
    environment:
      FLUENTD_CONF: fluentd.conf

  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  h2o:
    image: lkwg82/h2o-http2-server
    ports:
      - 8000:443
    volumes:
      - ./h2o/conf:/etc/h2o
      - ./h2o/log:/var/log/h2o
      - ./h2o/cert:/cert
      - ./h2o/www:/var/www

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db

  mongo-express:
    build: ./mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo
